### ISSUE TITLE
Finishing a story generates an error msg: "unknown option `quiet'"

### ISSUE THREAD

**Issue by mavericohm** [nebhale/git-pivotal-tracker-integration#11]
When I try to finish a story

```
bundle exec git finish
```

I get the following error

```
Deleting 52213347-fix-avatar-uploader... error: unknown option `quiet'
usage: git branch [options] [-r | -a] [--merged | --no-merged]
or: git branch [options] [-l] [-f] <branchname> [<start-point>]
or: git branch [options] [-r] (-d | -D) <branchname>...
or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

...

FAIL
```

**Comment by nebhale** [comment]
I suspect it just might be a back version of Git.  The project requires Git 1.8.2.1 (they're up to 1.8.3.1 now).  What version are you running?

**Comment by mavericohm** [comment]
This is it:

git version 1.7.8.4

I am not using the project anymore but that might be the reason for the exception. 

Thank you nebhale.

**Comment by nebhale** [comment]
Yup, that'd be it.  And no problem.
